"""Initial migration

Revision ID: 075e3cf26489
Revises: 49e5a7fce6b7
Create Date: 2024-10-13 17:47:42.871182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075e3cf26489'
down_revision = '49e5a7fce6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
