"""Initial migration

Revision ID: 0844af4ee468
Revises: 8740761c051d
Create Date: 2024-10-21 19:02:18.362610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0844af4ee468'
down_revision = '8740761c051d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
