"""Initial migration

Revision ID: 25ee40b68267
Revises: cb386408c659
Create Date: 2024-10-21 16:28:26.862850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ee40b68267'
down_revision = 'cb386408c659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
