"""Initial migration

Revision ID: 3e340d82b07c
Revises: 6b3e0c44049a
Create Date: 2024-10-13 17:55:09.870573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e340d82b07c'
down_revision = '6b3e0c44049a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
