"""Initial migration

Revision ID: 3e8265c7f3e0
Revises: 60f1a3df8793
Create Date: 2024-10-15 17:28:00.630332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8265c7f3e0'
down_revision = '60f1a3df8793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
