"""Initial migration

Revision ID: 49e5a7fce6b7
Revises: ad6ec76827bc
Create Date: 2024-10-13 17:46:52.557798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e5a7fce6b7'
down_revision = 'ad6ec76827bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
