"""Initial migration

Revision ID: 60f1a3df8793
Revises: 3e340d82b07c
Create Date: 2024-10-15 17:24:53.616451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f1a3df8793'
down_revision = '3e340d82b07c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
