"""Initial migration

Revision ID: 6389de43237e
Revises: b4e769557f8d
Create Date: 2024-10-21 16:47:16.671374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6389de43237e'
down_revision = 'b4e769557f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
