"""Initial migration

Revision ID: 68ffb9186dce
Revises: 25ee40b68267
Create Date: 2024-10-21 16:33:58.336369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ffb9186dce'
down_revision = '25ee40b68267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
