"""Initial migration

Revision ID: 6b3e0c44049a
Revises: a2b69b643da8
Create Date: 2024-10-13 17:49:41.492907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3e0c44049a'
down_revision = 'a2b69b643da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
