"""Initial migration

Revision ID: 8740761c051d
Revises: 6389de43237e
Create Date: 2024-10-21 16:50:38.279772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8740761c051d'
down_revision = '6389de43237e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('lv', sa.Integer(), nullable=False))
    op.add_column('districts', sa.Column('lv', sa.Integer(), nullable=False))
    op.add_column('provinces', sa.Column('lv', sa.Integer(), nullable=False))
    op.add_column('streets', sa.Column('lv', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streets', 'lv')
    op.drop_column('provinces', 'lv')
    op.drop_column('districts', 'lv')
    op.drop_column('cities', 'lv')
    # ### end Alembic commands ###
