"""Initial migration

Revision ID: 9a4f116aaf40
Revises: a0e8263ab1a5
Create Date: 2024-10-31 23:55:22.028966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4f116aaf40'
down_revision = 'a0e8263ab1a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functional_version', sa.Column('is_status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functional_version', 'is_status')
    # ### end Alembic commands ###
