"""Initial migration

Revision ID: a0e8263ab1a5
Revises: c5d521e21fdc
Create Date: 2024-10-31 23:44:10.385851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e8263ab1a5'
down_revision = 'c5d521e21fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functional_version', sa.Column('create_user', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functional_version', 'create_user')
    # ### end Alembic commands ###
