"""Initial migration

Revision ID: a2b69b643da8
Revises: 075e3cf26489
Create Date: 2024-10-13 17:48:37.963864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b69b643da8'
down_revision = '075e3cf26489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
