"""Initial migration

Revision ID: b4e769557f8d
Revises: e68bc091b284
Create Date: 2024-10-21 16:45:48.044552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e769557f8d'
down_revision = 'e68bc091b284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
