"""Initial migration

Revision ID: c5d521e21fdc
Revises: e01a74502a78
Create Date: 2024-10-31 23:32:23.193797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d521e21fdc'
down_revision = 'e01a74502a78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
