"""Initial migration

Revision ID: cb386408c659
Revises: f57276d1309a
Create Date: 2024-10-15 17:32:46.068984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb386408c659'
down_revision = 'f57276d1309a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendscircle_ibfk_1', 'friendsCircle', type_='foreignkey')
    op.drop_constraint('friendscircle_ibfk_3', 'friendsCircle', type_='foreignkey')
    op.drop_column('friendsCircle', 'comment_user_id')
    op.drop_column('friendsCircle', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendsCircle', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('friendsCircle', sa.Column('comment_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('friendscircle_ibfk_3', 'friendsCircle', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key('friendscircle_ibfk_1', 'friendsCircle', 'user', ['comment_user_id'], ['id'])
    # ### end Alembic commands ###
