"""Initial migration

Revision ID: e01a74502a78
Revises: 0844af4ee468
Create Date: 2024-10-29 21:01:01.976896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e01a74502a78'
down_revision = '0844af4ee468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_login', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('update_time', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('address_str', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('is_status', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=255), nullable=False))
    op.drop_column('user', 'createTime')
    op.drop_column('user', 'updateTime')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'address')
    op.drop_column('user', 'isStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('address', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('user', sa.Column('avatar', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('updateTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('createTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'is_status')
    op.drop_column('user', 'address_str')
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'is_login')
    # ### end Alembic commands ###
