"""Initial migration

Revision ID: e68bc091b284
Revises: 68ffb9186dce
Create Date: 2024-10-21 16:34:45.734973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68bc091b284'
down_revision = '68ffb9186dce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
