"""Initial migration

Revision ID: f57276d1309a
Revises: 3e8265c7f3e0
Create Date: 2024-10-15 17:30:46.627993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57276d1309a'
down_revision = '3e8265c7f3e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
